<?php
return [
    'icon-framework'                  => \kartik\icons\Icon::FAS,
    'largePageSize'                   => 35,
    'pageSize'                        => 25,
    'smallPageSize'                   => 15,
    'adminEmail'                      => 'admin@kattan.net',
    'uploadDirectory'                 => 'uploads',
    'uploadDirectoryMail'             => 'uploads/invoices',
    'uploadDirectoryArticle'          => 'images/article_file',
    'uploadDirectoryCategory'         => 'images/category',
    'uploadDirectoryBookGalleryPhoto' => 'images/book_gallery',
    'uploadDirectoryBookGalleryPdf'   => 'pdf/book_gallery',
    'prefixOriginal'                  => 'o_',
    'prefixThumbnail'                 => 't_',
    'thumbnailWidth'                  => 150,
    'thumbnailHeight'                 => 90,
    'months'                          => [
        1  => 'Januar',
        2  => 'Februar',
        3  => 'März',
        4  => 'April',
        5  => 'Mai',
        6  => 'Juni',
        7  => 'Juli',
        8  => 'August',
        9  => 'September',
        10 => 'Oktober',
        11 => 'Novermber',
        12 => 'Dezember',
    ],
];
