<?php
$passwd = Yii::$app->security->generatePasswordHash('Meinaicovo1');
return [
    [
        "id"                   => 1,
        "username"             => "admin",
        "first_name"           => "admin",
        "last_name"            => "admin",
        "password"             => $passwd,
        "password_reset_token" => null,
        "email"                => "admin@aicovo.com",
        "active_from"          => date('Y-m-d H:i',strtotime("-1 month")),
        "active_until"         => null,
        "created_at"           => "2018-06-25 12:39:51",
        "updated_at"           => null,
    ],
    [
        "id"                   => 2,
        "username"             => "user",
        "first_name"           => "firstname",
        "last_name"            => "lastName",
        "password"             => $passwd,
        "password_reset_token" => null,
        "email"                => "user@aicovo.com",
        "active_from"          => date('Y-m-d H:i',strtotime("-1 month")),
        "active_until"         => null,
        "created_at"           => "2018-06-25 13:01:14",
        "updated_at"           => "2018-06-25 13:01:14",
    ],
    [
        "id"                   => 3,
        "username"             => "hugo",
        "first_name"           => "vhugo",
        "last_name"            => "nhugo",
        "password"             => $passwd,
        "password_reset_token" => null,
        "email"                => "hugo@gmx.de",
        "active_from"          => date('Y-m-d H:i',strtotime("-1 month")),
        "active_until"         => date('Y-m-d H:i',strtotime("+1 month")),
        "created_at"           => "2018-06-25 15:32:03",
        "updated_at"           => "2018-07-06 08:45:28",
    ],
    [
        "id"                   => 4,
        "username"             => "deactivate",
        "first_name"           => "deactivate",
        "last_name"            => "deactivate",
        "password"             => $passwd,
        "password_reset_token" => null,
        "email"                => "deactive@gmx.de",
        "active_from"          => date('Y-m-d H:i',strtotime("-2 month")),
        "active_until"         => date('Y-m-d H:i',strtotime("-1 month")),
        "created_at"           => "2018-06-25 15:32:03",
        "updated_at"           => "2018-07-06 08:45:28",
    ],
    [
        "id"                   => 5,
        "username"             => "set.password",
        "first_name"           => "Set",
        "last_name"            => "Password",
        "password"             => null,
        "password_reset_token" => "VClDZXmLGlx9n8cOadytE828yRZxLknC_" . time(),
        "email"                => "max.kirmair@aicovo.com",
        "active_from"          => date('Y-m-d H:i',strtotime("-30 minute")),
        "active_until"         => null,
        "created_at"           => "2018-10-12 14:32:13",
        "updated_at"           => "2019-01-15 09:35:48",
    ],
];
