<?php
return [
    [
        "name"        => "admin",
        "type"        => 1,
        "description" => null,
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1539265619,
        "updated_at"  => 1539265619,
    ],
    [
        "name"        => "Assistenz",
        "type"        => 1,
        "description" => "blabla",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544524147,
        "updated_at"  => 1544524147,
    ],
    [
        "name"        => "Werbehinweise",
        "type"        => 1,
        "description" => "Ermöglicht das Anpassen der Inhalte von Werbehinweisen für die Schaltung von Stellenanzeigen und das Einsehen der zugehörigen Statistiken",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544802015,
        "updated_at"  => 1544802015,
    ],
    [
        "name"        => "Ausschreibungen",
        "type"        => 1,
        "description" => "Ermöglicht das verwalten der Themenbereiche und Funktionen für Ausschreibungen",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1539347468,
        "updated_at"  => 1539347468,
    ],
    [
        "name"        => "*.*",
        "type"        => 2,
        "description" => null,
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1539265619,
        "updated_at"  => 1539265619,
    ],
    [
        "name"        => "praktikant",
        "type"        => 1,
        "description" => "Praktikant",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => null,
        "updated_at"  => 1530262249,
    ],
    [
        "name"        => "search.*",
        "type"        => 2,
        "description" => "Alle Funktionen der Suche",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544620967,
        "updated_at"  => 1544620967,
    ],
    [
        "name"        => "user-stamm.*",
        "type"        => 2,
        "description" => "Kundenverwaltung",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544524029,
        "updated_at"  => 1544524029,
    ],
    [
        "name"        => "career-website.*",
        "type"        => 2,
        "description" => "Karriere Webseiten",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544524098,
        "updated_at"  => 1544524098,
    ],
    [
        "name"        => "base-data.*",
        "type"        => 2,
        "description" => "Ausschreibung - Stammdaten",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1539347345,
        "updated_at"  => 1539347345,
    ],
    [
        "name"        => "company-type.*",
        "type"        => 2,
        "description" => "Ausschreibung - Firmenverwaltung",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544802015,
        "updated_at"  => 1544802015,
    ],
    [
        "name"        => "role.*",
        "type"        => 2,
        "description" => "Ausschreibung - Rollenverwaltung",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544802015,
        "updated_at"  => 1544802015,
    ],
    [
        "name"        => "modul-user-detail-contact.*",
        "type"        => 2,
        "description" => "Kunden Ansprechpartner verwalten",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544524074,
        "updated_at"  => 1544524074,
    ],
    [
        "name"        => "category.*",
        "type"        => 2,
        "description" => "Ausschreibung - Themenbereiche",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1539347312,
        "updated_at"  => 1539347312,
    ],
    [
        "name"        => "function.*",
        "type"        => 2,
        "description" => "Ausschreibung - Funktionen",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1539347345,
        "updated_at"  => 1539347345,
    ],
    [
        "name"        => "stelle-ausschreibung-modal.*",
        "type"        => 2,
        "description" => "Anpassen der Inhalte von Werbehinweisen für die Schaltung von Stellenanzeigen und Anzeigen der Statistiken dieser",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544802015,
        "updated_at"  => 1544802015,
    ],
    [
        "name"        => "attachment.*",
        "type"        => 2,
        "description" => "Ausschreibung - Zusatz",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1539347345,
        "updated_at"  => 1539347345,
    ],
    [
        "name"        => "Suchen",
        "type"        => 3,
        "description" => "Admin Bereich Durchsuchen",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544620986,
        "updated_at"  => 1544620986,
    ],
    [
        "name"        => "Assistenz1",
        "type"        => 3,
        "description" => "Anna",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544524112,
        "updated_at"  => 1544524112,
    ],
    [
        "name"        => "Ausschreibungen Verwalten",
        "type"        => 3,
        "description" => "Ermöglicht das verwalten der Themenbereiche und Funktionen für Ausschreibungen",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1539347405,
        "updated_at"  => 1539347405,
    ],
    [
        "name"        => "Werbehinweise verwalten und Statistiken einsehen",
        "type"        => 3,
        "description" => "Ermöglicht das Anpassen der Inhalte von Werbehinweisen für die Schaltung von Stellenanzeigen und das Einsehen der zugehörigen Statistiken",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544802015,
        "updated_at"  => 1544802015,
    ],
    [
        "name"        => "Projekte",
        "type"        => 5,
        "description" => "Ermöglicht das Anpassen der Inhalte von Werbehinweisen für die Schaltung von Stellenanzeigen und das Einsehen der zugehörigen Statistiken",
        "rule_name"   => null,
        "data"        => null,
        "created_at"  => 1544802015,
        "updated_at"  => 1544802015,
    ],
];