<?php
$auth_item = [
	[
		"name" => "maxTask",
		"type" => 3,
		"description" => "asdasdadsd",
		"rule_name" => NULL,
		"data" => NULL,
		"created_at" => 1530513959,
		"updated_at" => 1530513959,
	],
	[
		"name" => "customerTask",
		"type" => 3,
		"description" => NULL,
		"rule_name" => NULL,
		"data" => NULL,
		"created_at" => 1530123140,
		"updated_at" => 1530123140,
	],
	[
		"name" => "praktikantTask",
		"type" => 3,
		"description" => "Aufgaben des Praktikanten",
		"rule_name" => NULL,
		"data" => NULL,
		"created_at" => NULL,
		"updated_at" => NULL,
	],
	[
		"name" => \common\models\auth\AuthItem::SUPER_PERMISSION,
		"type" => 2,
		"description" => NULL,
		"rule_name" => NULL,
		"data" => NULL,
		"created_at" => 1529923191,
		"updated_at" => 1529923191,
	],
	[
		"name" => "user-stamm.*",
		"type" => 2,
		"description" => NULL,
		"rule_name" => NULL,
		"data" => NULL,
		"created_at" => NULL,
		"updated_at" => NULL,
	],
	[
		"name" => "user-stamm.login",
		"type" => 2,
		"description" => "Einloggen beim Kunden",
		"rule_name" => NULL,
		"data" => NULL,
		"created_at" => 1529923191,
		"updated_at" => 1529923191,
	],
	[
		"name" => "admin",
		"type" => 1,
		"description" => "darf alles ",
		"rule_name" => NULL,
		"data" => NULL,
		"created_at" => 1529923191,
		"updated_at" => 1529923191,
	],
	[
		"name" => "praktikant",
		"type" => 1,
		"description" => "Praktikant",
		"rule_name" => NULL,
		"data" => NULL,
		"created_at" => NULL,
		"updated_at" => 1530262249,
	],
	[
		"name" => "customerManager",
		"type" => 1,
		"description" => "Verwalter von Kunden Kontos2",
		"rule_name" => NULL,
		"data" => NULL,
		"created_at" => NULL,
		"updated_at" => 1530623560,
	],
];
return $auth_item;
?>