<?php
return array(
    array(
        "modaccid" => 10,
        "aktiv" => 1,
        "secure_hash" => "123",
        "userid" => 1,
        "modulid" => 1,
        "bewerber_modulid" => 0,
        "pool_modulid" => 0,
        "stellen_modulid" => 0,
        "profil_modulid" => 0,
        "sonstiges_modulid" => 0,
        "modulid_fut" => 0,
        "bewerber_modulid_fut" => 0,
        "pool_modulid_fut" => 0,
        "stellen_modulid_fut" => 0,
        "profil_modulid_fut" => 0,
        "sonstiges_modulid_fut" => 0,
        "zahlung" => "",
        "zahlung_fut" => "",
        "buchungstart" => "0000-00-00",
        "buchungende" => "0000-00-00",
        "faelligkeit" => "0000-00-00",
        "pool_faelligkeit" => "0000-00-00",
        "veroeffentlichen" => 0,
        "testaccount" => 0,
    ),
    array(
        "modaccid" => 11,
        "aktiv" => 1,
        "secure_hash" => "123",
        "userid" => 2,
        "modulid" => 1,
        "bewerber_modulid" => 0,
        "pool_modulid" => 0,
        "stellen_modulid" => 0,
        "profil_modulid" => 0,
        "sonstiges_modulid" => 0,
        "modulid_fut" => 0,
        "bewerber_modulid_fut" => 0,
        "pool_modulid_fut" => 0,
        "stellen_modulid_fut" => 0,
        "profil_modulid_fut" => 0,
        "sonstiges_modulid_fut" => 0,
        "zahlung" => "",
        "zahlung_fut" => "",
        "buchungstart" => "0000-00-00",
        "buchungende" => "0000-00-00",
        "faelligkeit" => "0000-00-00",
        "pool_faelligkeit" => "0000-00-00",
        "veroeffentlichen" => 0,
        "testaccount" => 0,
    ),
    array(
        "modaccid" => 12,
        "aktiv" => 1,
        "secure_hash" => "123",
        "userid" => 3,
        "modulid" => 1,
        "bewerber_modulid" => 0,
        "pool_modulid" => 0,
        "stellen_modulid" => 0,
        "profil_modulid" => 0,
        "sonstiges_modulid" => 0,
        "modulid_fut" => 0,
        "bewerber_modulid_fut" => 0,
        "pool_modulid_fut" => 0,
        "stellen_modulid_fut" => 0,
        "profil_modulid_fut" => 0,
        "sonstiges_modulid_fut" => 0,
        "zahlung" => "",
        "zahlung_fut" => "",
        "buchungstart" => "0000-00-00",
        "buchungende" => "0000-00-00",
        "faelligkeit" => "0000-00-00",
        "pool_faelligkeit" => "0000-00-00",
        "veroeffentlichen" => 0,
        "testaccount" => 1,
    ),
);
