<?php
return array(
    array(
        "sub_user_id" => 599,
        "anrede" => "Herr",
        "titel" => 0,
        "vorname" => "Hans",
        "nachname" => "Peter",
        "abteilung" => "Personalbetreuung",
        "position" => "",
        "email" => "hans.peter@web.de",
        "ansprechpartner" => 0,
        "role_id" => 0,
    ),
    array(
        "sub_user_id" => 885,
        "anrede" => "Frau",
        "titel" => 0,
        "vorname" => "Hüft",
        "nachname" => "Gold",
        "abteilung" => "Ausbildung",
        "position" => "Ausbildungsleitung",
        "email" => "hueft.gold@email.de",
        "ansprechpartner" => 0,
        "role_id" => 0,
    ),
    array(
        "sub_user_id" => 943,
        "anrede" => "Frau",
        "titel" => 0,
        "vorname" => "Detlef",
        "nachname" => "Gut",
        "abteilung" => "Abteilung",
        "position" => "Position",
        "email" => "detlef@gut.de",
        "ansprechpartner" => 0,
        "role_id" => 0,
    ),
);
