<?php
return [
    [
        "id" => 1,
        "username" => "hans.wurst.frontend",
        "first_name" => "Hans",
        "last_name" => "Wurst",
        "password" => '$2y$13$SnTKBPyL5xrdn9jUe4PfI.Mq/S6zlPYoVHpmztvqNTdnKyc2Q5wbG',
        "password_reset_token" => NULL,
        "email" => "hans.wurst@aicovo.com",
        "created_at" => "2019-02-12 14:19:12",
        "updated_at" => "2019-02-12 14:43:25",
    ],
    [
        "id" => 2,
        "username" => "max.mustermann.frontend",
        "first_name" => "Max",
        "last_name" => "Mustermann",
        "password" => '$2y$13$SnTKBPyL5xrdn9jUe4PfI.Mq/S6zlPYoVHpmztvqNTdnKyc2Q5wbG',
        "password_reset_token" => NULL,
        "email" => "max.mustermax@aicovo.com",
        "created_at" => "2019-02-12 15:39:02",
        "updated_at" => "2019-02-12 15:39:02",
    ],
    [
        "id" => 3,
        "username" => "peter.mueller.frontend",
        "first_name" => "Peter",
        "last_name" => "Müller",
        "password" => '$2y$13$SnTKBPyL5xrdn9jUe4PfI.Mq/S6zlPYoVHpmztvqNTdnKyc2Q5wbG',
        "password_reset_token" => NULL,
        "email" => "peter.mueller@aicovo.com",
        "created_at" => "2019-02-12 15:39:29",
        "updated_at" => "2019-02-12 15:39:29",
    ],
];
