<?php
return array(
    array(
        "id" => 1,
        "subId" => 0,
        "benutzername" => "mail@cool-firma.de",
        "passwort" => "",
        "passwortNeu" => "",
        "subdomain" => "",
        "datum_anmeldung" => "2018-08-22 09:27:14",
        "kuerzel" => "",
    ),
    array(
        "id" => 2,
        "subId" => 0,
        "benutzername" => "schlemmer@doof.com",
        "passwort" => "",
        "passwortNeu" => "",
        "subdomain" => "",
        "datum_anmeldung" => "2018-08-22 09:27:46",
        "kuerzel" => "",
    ),
    array(
        "id" => 3,
        "subId" => 0,
        "benutzername" => "Unternehmen@gmail.com",
        "passwort" => "",
        "passwortNeu" => "",
        "subdomain" => "",
        "datum_anmeldung" => "2018-08-22 09:27:47",
        "kuerzel" => "",
    ),
    array(
        "id" => 599,
        "subId" => 1,
        "benutzername" => "hans.peter@web.de",
        "passwort" => "",
        "passwortNeu" => "",
        "subdomain" => "",
        "datum_anmeldung" => "2018-08-22 09:28:16",
        "kuerzel" => "",
    ),
    array(
        "id" => 885,
        "subId" => 2,
        "benutzername" => "hueft.gold@email.de",
        "passwort" => "",
        "passwortNeu" => "",
        "subdomain" => "",
        "datum_anmeldung" => "2018-08-22 09:28:30",
        "kuerzel" => "",
    ),
    array(
        "id" => 943,
        "subId" => 0,
        "benutzername" => "detlef@gut.de",
        "passwort" => "",
        "passwortNeu" => "",
        "subdomain" => "",
        "datum_anmeldung" => "2018-08-22 09:28:47",
        "kuerzel" => "",
    ),
);
