<?php
return array(
    array(
        "id" => 1,
        "kundenid" => "",
        "werber_id" => 17,
        "anrede" => "frau",
        "titel" => "0",
        "vorname" => "Monika",
        "nachname" => "Hirsch",
        "logo" => NULL,
        "firma" => "Coole Firma GmbH",
        "strasse" => "",
        "plz" => "23423",
        "ort" => "München",
        "land" => "1",
        "email" => "mail@cool-firma.de",
        "homepage" => "",
        "telefon_land" => 1,
        "telefon_ort" => "",
        "telefon_nr" => "",
        "mobil_land" => 0,
        "mobil_ort" => "",
        "mobil_nr" => "",
        "fax_land" => 1,
        "fax_ort" => "",
        "fax_nr" => "",
    ),
    array(
        "id" => 2,
        "kundenid" => "",
        "werber_id" => 52,
        "anrede" => "herr",
        "titel" => "0",
        "vorname" => "Horst",
        "nachname" => "Schlemmer",
        "logo" => NULL,
        "firma" => "Doof Ltd.",
        "strasse" => "",
        "plz" => "32131",
        "ort" => "Bochum",
        "land" => "1",
        "email" => "schlemmer@doof.com",
        "homepage" => "",
        "telefon_land" => 1,
        "telefon_ort" => "",
        "telefon_nr" => "",
        "mobil_land" => 0,
        "mobil_ort" => "",
        "mobil_nr" => "",
        "fax_land" => 1,
        "fax_ort" => "",
        "fax_nr" => "",
    ),
    array(
        "id" => 3,
        "kundenid" => "",
        "werber_id" => 52,
        "anrede" => "herr",
        "titel" => "0",
        "vorname" => "Peter",
        "nachname" => "Müller",
        "logo" => NULL,
        "firma" => "Unternehmen",
        "strasse" => "",
        "plz" => "50827",
        "ort" => "Köln",
        "land" => "1",
        "email" => "Unternehmen@gmail.com",
        "homepage" => "",
        "telefon_land" => 1,
        "telefon_ort" => "",
        "telefon_nr" => "",
        "mobil_land" => 0,
        "mobil_ort" => "",
        "mobil_nr" => "",
        "fax_land" => 0,
        "fax_ort" => "",
        "fax_nr" => "",
    ),
);
