<?php
return [
    [
        "id"                              => 15,
        "public_key"                      => "zUqOMuUaWw9dUrWpJ8tz0XPtFAeanLiDi7D5jdDCcqoMHFtG3s",
        "company_name"                    => "test Firma",
        "street"                          => "test",
        "house_number"                    => "test",
        "zip_code"                        => "354244",
        "city"                            => "test",
        "country_id"                      => 1,
        "salutation"                      => "herr",
        "first_name"                      => "sam",
        "last_name"                       => "test",
        "base_date"                       => "2018-11-20",
        "application_trainee_count"       => 20,
        "application_dual_students_count" => 1,
        "application_executives_count"    => 20,
        "admin_count"                     => 5,
        "person_responsible_count"        => 43,
        "evaluator_count"                 => 443,
        "vacancy_trainee_count"           => 40,
        "vacancy_dual_students_count"     => 2,
        "vacancy_executives_count"        => 40,
        "employee_count"                  => 1000,
        "location_count"                  => 2,
        "company_count"                   => 1,
        "created_at"                      => "2019-01-21 09:29:48",
        "updated_at"                      => "2019-01-23 13:12:41",
    ],
];
